name: CustomSpawners
author: Codebucket
version: 1.0 Release
main: de.codebucket.customspawners.CustomSpawners
website: http://www.codebucket.de
commands:
     customspawners:
          description: CustomSpawners main command
          usage: /<command>