name: CustomSpawners
author: Codebucket
version: 1.5 Release
main: de.codebucket.customspawners.CustomSpawners
load: POSTWORLD
website: http://www.codebucket.de
commands:
     customspawners:
          description: CustomSpawners main command
          usage: /<command>